[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ware-ops-pipes"
version = "0.2.0"
description = "Context-aware synthesis of optimization pipelines for warehouse optimization."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
dependencies = [
    "ware-ops-algos @ git+https://github.com/kit-dsm/ware_ops_algos.git@4edd3d9a23e170ef29c2ca5944107265d39cdfeb",
    "cls-luigi==0.1.1",
    "luigi==3.6.0",
    "pandas"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
]
eval = [
    "jupyter",
    "tqdm",
    "orjson",
    "seaborn",
    "jinja2",
    "lxml",
    "pyarrow"
]
docs = [
    "sphinx",
    "sphinx-copybutton",
    "furo",
]
[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
