from __future__ import annotations

import re
from pathlib import Path
from pprint import pformat

from ware_ops_algos.algorithms.algorithm_cards import (
    load_packaged_algo_cards,
)


SUPPORTED_BASES = {
    "SeedBatching",
    "LocalSearchBatching",
    "ClarkAndWrightBatching"
}

PACKAGE_NAME = (
    "ware_ops_pipes.pipelines.subproblems.batching.generated"
)

OUTPUT_DIR = (
    Path(__file__).parent
    / "pipelines"
    / "subproblems"
    / "batching"
    / "generated"
)


def to_snake_case(name: str) -> str:
    """Convert a Python class name into a valid module name."""
    value = re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()
    value = re.sub(r"[^a-z0-9_]", "_", value)

    if not value:
        raise ValueError(f"Cannot create module name from {name!r}")

    if value[0].isdigit():
        value = f"configured_{value}"

    return value


def render_seed_component(
    component_name: str,
    implementation: dict,
) -> str:
    seed_criterion = implementation["seed_criterion"]
    similarity_measure = implementation["similarity_measure"]

    return f'''\
# This file is generated by ware_ops_pipes/generate_configured_components.py. Do not edit manually.

from ware_ops_algos.algorithms import (
    SEED_CRITERIA,
    SIMILARITY_MEASURES,
)

from ..configured_batching import ConfiguredSeedBatching
from ._support import get_algorithm_card


class {component_name}(ConfiguredSeedBatching):
    abstract = False

    algorithm_card = get_algorithm_card({component_name!r})

    seed_criterion_cls = SEED_CRITERIA[{seed_criterion!r}]
    similarity_measure_cls = SIMILARITY_MEASURES[{similarity_measure!r}]
'''


def render_local_search_component(
    component_name: str,
    implementation: dict,
) -> str:
    routing_class = implementation["routing_class"]
    start_batching_class = implementation["start_batching_class"]

    neighborhoods = implementation.get(
        "neighborhoods",
        ["SwapNeighborhood", "ShiftNeighborhood"],
    )

    neighborhood_lines = "\n".join(
        f"        resolve_algorithm_class({name!r}),"
        for name in neighborhoods
    )

    return f'''\
# This file is generated. Do not edit manually.

from ware_ops_pipes.pipelines.resolve_algo_class_names import (
    resolve_algorithm_class,
)

from ..configured_batching import ConfiguredLocalSearchBatching
from ._support import get_algorithm_card


class {component_name}(ConfiguredLocalSearchBatching):
    abstract = False

    algorithm_card = get_algorithm_card({component_name!r})

    routing_class = resolve_algorithm_class({routing_class!r})
    start_batching_class = resolve_algorithm_class(
        {start_batching_class!r}
    )

    neighborhood_classes = [
{neighborhood_lines}
    ]
'''


def render_cw_component(
    component_name: str,
    implementation: dict,
) -> str:
    routing_class = implementation["routing_class"]

    return f'''\
# This file is generated. Do not edit manually.

from ware_ops_pipes.pipelines.resolve_algo_class_names import (
    resolve_algorithm_class,
)

from ..configured_batching import ConfiguredClarkAndWrightBatching
from ._support import get_algorithm_card


class {component_name}(ConfiguredClarkAndWrightBatching):
    abstract = False

    algorithm_card = get_algorithm_card({component_name!r})

    routing_class = resolve_algorithm_class({routing_class!r})
'''


def render_component(
    component_name: str,
    implementation: dict,
) -> str:
    base = implementation["class_name"]

    if base == "SeedBatching":
        return render_seed_component(
            component_name,
            implementation,
        )

    if base == "LocalSearchBatching":
        return render_local_search_component(
            component_name,
            implementation,
        )

    if base == "ClarkAndWrightBatching":
        return render_cw_component(
            component_name,
            implementation
        )

    raise ValueError(
        f"No generator implemented for configured base {base!r}"
    )


def write_support_module() -> None:
    support_source = '''\
# This file is generated. Do not edit manually.

from functools import lru_cache

from ware_ops_algos.algorithms.algorithm_cards import (
    load_packaged_algo_cards,
)


@lru_cache(maxsize=1)
def _cards_by_name():
    return {
        card.algo_name: card
        for card in load_packaged_algo_cards()
    }


def get_algorithm_card(name: str):
    try:
        return _cards_by_name()[name]
    except KeyError as exc:
        raise ValueError(
            f"Configured algorithm card {name!r} was not found."
        ) from exc
'''

    (OUTPUT_DIR / "_support.py").write_text(
        support_source,
        encoding="utf-8",
    )


def remove_stale_modules(expected_files: set[str]) -> None:
    for path in OUTPUT_DIR.glob("*.py"):
        if path.name not in expected_files:
            path.unlink()


def generate_configured_components() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    cards = load_packaged_algo_cards()

    generated_modules: dict[str, str] = {}
    expected_files = {
        "__init__.py",
        "_support.py",
        "index.py",
    }

    for card in cards:
        implementation = card.implementation or {}
        base = implementation.get("class_name")

        if base not in SUPPORTED_BASES:
            continue

        component_name = implementation.get(
            "component_name",
            card.algo_name,
        )

        if component_name != card.algo_name:
            raise ValueError(
                "The configured component name must match the "
                f"algorithm-card name: {component_name!r} != "
                f"{card.algo_name!r}"
            )

        module_name = to_snake_case(component_name)
        filename = f"{module_name}.py"

        if filename in expected_files:
            raise ValueError(
                f"Duplicate generated module filename: {filename}"
            )

        source = render_component(
            component_name=component_name,
            implementation=implementation,
        )

        (OUTPUT_DIR / filename).write_text(
            source,
            encoding="utf-8",
        )

        expected_files.add(filename)
        generated_modules[component_name] = (
            f"{PACKAGE_NAME}.{module_name}"
        )

    (OUTPUT_DIR / "__init__.py").write_text(
        "# Generated CLS-Luigi configurations.\n",
        encoding="utf-8",
    )

    write_support_module()

    index_source = (
        "# This file is generated. Do not edit manually.\n\n"
        f"CONFIGURED_COMPONENT_MODULES = {pformat(generated_modules, sort_dicts=True)}\n"
    )

    (OUTPUT_DIR / "index.py").write_text(
        index_source,
        encoding="utf-8",
    )

    remove_stale_modules(expected_files)

    print(
        f"Generated {len(generated_modules)} configured "
        f"CLS-Luigi components in {OUTPUT_DIR}"
    )


if __name__ == "__main__":
    generate_configured_components()